# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"batch_hard_triplet_loss": "triplet_loss.ipynb",
         "batch_all_triplet_loss": "triplet_loss.ipynb"}

modules = ["losses.py"]

doc_url = "https://NegatioN.github.io/OnlineMiningTripletLoss/"

git_url = "https://github.com/NegatioN/OnlineMiningTripletLoss/tree/master/"

def custom_doc_links(name): return None
